### ISSUE TITLE
A small change is needed in EventHubWebModule.cs file

### ISSUE THREAD

**Issue by radrad** [volosoft/eventhub#100]
In this file:
src\EventHub.Web\EventHubWebModule.cs

Line 177 needs a small change from:
`options.FileSets.ReplaceEmbeddedByPhysical<EventHubDomainSharedModule>(Path.Combine(hostingEnvironment.ContentRootPath, $"..{Path.DirectorySeparatorChar}EventHub.Domain"));;`
to:
`options.FileSets.ReplaceEmbeddedByPhysical<EventHubDomainSharedModule>(Path.Combine(hostingEnvironment.ContentRootPath, $"..{Path.DirectorySeparatorChar}EventHub.Domain.Shared"));;`

I am not sure how significant is this change and when would this be a problem? 
Is this about allowing a module that is present in VS solution to change files under these folders like new Page or Component and it will be recognized within depending module and the GUI will render dynamically. 
This would not be needed if there is a binary dependency like nuget where some of files needed for GUI will be loaded from resources

**Comment by hikalkan** [comment]
Thanks @radrad for reporting. We will fix it.

**Comment by EngincanV** [comment]
> Is this about allowing a module that is present in VS solution to change files under these folders like new Page or Component and it will be recognized within depending module and the GUI will render dynamically.

Actually, the `ReplaceEmbeddedByPhysical` method makes it possible to directly use the physical file at the development time, and thanks to that we don't need to stop the application and re-run again for every embedded file change (such as JavaScript).

> https://docs.abp.io/en/abp/latest/Virtual-File-System#dealing-with-embedded-files-during-development

**Comment by radrad** [comment]
Thanks @EngincanV.
So for this small problem when we had EventHub.Domain for <EventHubDomainSharedModule>, what would surface as a problem at development time (I suppose you mean build it in debug mode and run).
And what is it that proper value (EventHub.Domain.Shared) fixes.

Can you please explain the mechanizam that controlls release buld vs. debug build? Is there an explicit decision within Volosoft virtual system where there is a selection for debug time compiled code and this is where ReplaceEmbeddedByPhysical settings is used, while in release mode we load things from embeded resources.

So is this fix meaningfull since EventHubDomainSharedModule containes only .cs code which needs be re-compiled.

Can I load my razor view, component from a remote microservice and cache it on the host side. 
I would like to create customizable solution per tenant to possibly load his/her specific widget/view component with specialized data retrieved from the app service customized for this tenant. So I need customization tenant for both GUI and API/DB layer. I am talking about tiny change compared to the same edition that other tenants have (imagine I want o provide custom features that are optional on top of an edition. How would one build such customization.
There is a research paper about using customization microservice for that:
[Using Microservices to Customize Multi-Tenant SaaS: From Intrusive to Non-Intrusive](https://www.semanticscholar.org/paper/Using-Microservices-to-Customize-Multi-Tenant-SaaS%3A-Song-Nguyen/48c4bcc3b924902f20b8ba39f1d30abbbb376668) and a project on github [[eShopOnContainersCustomised](https://github.com/nguyenhongphu/eShopOnContainersCustomised)](https://github.com/nguyenhongphu/eShopOnContainersCustomised)
