### ISSUE TITLE
Revise email content and visuals for EventHub emails

### ISSUE THREAD

**Issue by hikalkan** [volosoft/eventhub#30]

**Comment by hikalkan** [comment]
@armgnunlu please check you and decide if they are good or not.

**Comment by ebicoglu** [comment]
@braim23 you wait for @armgnunlu, he'll send you the email template, then you'll update it on EventHub solution
you can ask to @EngincanV

**Comment by melisplatin** [comment]
![E-Mail TemplateV1](https://user-images.githubusercontent.com/79847445/165089206-6ead3467-acc9-45a5-9165-90959ea8647d.png)
![E-Mail TemplateV2](https://user-images.githubusercontent.com/79847445/165089211-9465fead-555f-4de7-8c89-cc5b18a87b20.png)

Design file: https://www.figma.com/file/vaGDRNj48O6G7dnKOdm8Os/New-Design?node-id=1201%3A4413

**Comment by melisplatin** [comment]
Can you help with coding these e-mail templates? @halimekarayay

**Comment by ebicoglu** [comment]
https://github.com/volosoft/eventhub
