### ISSUE TITLE
There is a TLS certificate problem

### ISSUE THREAD

**Issue by berkansasmaz** [volosoft/eventhub#73]
- [ ] https://account.openeventhub.com/account/manage

<img width="1680" alt="Screen Shot 2021-11-17 at 16 22 21" src="https://user-images.githubusercontent.com/31216880/142208681-7af7cd7d-d5ec-42b4-85cf-c27d174f0d94.png">

**Comment by enisn** [comment]
Also, account.openeventhub.com can't be visited on chromium-based browsers.
![image](https://user-images.githubusercontent.com/23705418/146015168-a1efbc74-0a0f-4764-bbff-984dc61c7516.png)
