### ISSUE TITLE
Upgrade EventHub to ABP 5.0 stable

### ISSUE THREAD

**Issue by hikalkan** [volosoft/eventhub#80]

**Comment by EngincanV** [comment]
@berkansasmaz Can you remove the following lines when upgrading to 5.0 stable?

> There was a problem in v5.0-rc.1 for `Volo.Abp.EntityFrameworkCore.PostgreSql`. Therefore, the following lines were added.

* https://github.com/volosoft/eventhub/blob/main/src/EventHub.EntityFrameworkCore/EventHub.EntityFrameworkCore.csproj#L23

* https://github.com/volosoft/eventhub/blob/main/src/EventHub.EntityFrameworkCore/EntityFrameworkCore/EventHubEntityFrameworkCoreModule.cs#L35-L37
