### ISSUE TITLE
Test: Integrate CMS Kit comments to EventHub

### ISSUE THREAD

**Issue by hikalkan** [volosoft/eventhub#94]
See https://github.com/volosoft/eventhub/pull/93

**Comment by gizemmutukurt** [comment]
1.Comments can be made by clicking the submit button. OK.
2.Comment can be updated with the edit button. OK.
3.Comment can be deleted with delete button. OK.
4.Edited comments may be cancelled. OK.
5.A warning message is given when an empty comment is entered. OK.
6.A confirmation pop-up appears when the comment is requested to be deleted. (Yes/cancel) OK.
7. Comment can be replied. OK.
8.Cancel button is not in button view NOK 
![cancelbutton](https://user-images.githubusercontent.com/99716457/154427242-d5eadc46-a9dd-4bb3-b5a1-4c59981132e6.PNG)
9.Cancel button and Send button font size is incompatible. NOK
![cancelbutton](https://user-images.githubusercontent.com/99716457/154427242-d5eadc46-a9dd-4bb3-b5a1-4c59981132e6.PNG)
10. Text field zoom cursor does not work. NOK
![commenttext](https://user-images.githubusercontent.com/99716457/154429844-e57e4261-28c7-4bf2-b7eb-8c059eed192c.PNG)
11.It could be nicer if the view in the date field looks like 3 days ago. 
12. Edit and delete button places can be changed.
13.Displaying the comment field in a nested window does not look good. 
14.When the Reply button is clicked and the edit button is clicked, another one should be closed. NOK
15.When the Reply and edit buttons are clicked repeatedly and one of them is saved, it closes in two windows. NOK
16.The username is too big and bold. 
17.Comment made can be viewed by a different user. OK
18.The comment made can be replied by a different user. OK
19.Comment made cannot be edited by a different user. OK
20.The comment cannot be deleted by a different user. OK.
21.When a comment is edited, other edited windows should be closed. NOK
22.The user can only edit and delete the comments they have added. OK.
23.After the second comment, the reply button is also displayed at the bottom.
24.The last comment is displayed at the top. OK
25.Cancel button and Update button font size is incompatible. NOK.
26.It can be a feature of liking the comment

**Comment by enisn** [comment]
Most of them are related with CMS Kit
