### ISSUE TITLE
Test: Add limitations for free account

### ISSUE THREAD

**Issue by hikalkan** [volosoft/eventhub#98]
https://github.com/volosoft/eventhub/pull/90

**Comment by gizemmutukurt** [comment]
Bugs, see #90

**Comment by gizemmutukurt** [comment]
- Max. 2 events in a year. OK.
- maximum 2 tracks in an event OK.
- maximum 1,000 attendees to an event. OK.
- Validity of premium features when upgraded to premium package. OK.
- Reflecting on the web when the values ​​in the package properties are changed in the code. OK.
- Increasing the number of packages. OK.
- Extension option when package's end date approaches.OK
- You can view the bugs in other tests in #90
